### ISSUE TITLE
Support for topics (or event-groups).

### ISSUE THREAD

**Issue by adrianvoica** [developit/mitt#127]
Please add support for registering event-groups (or topics), just like the '*' event type, but with a prefixed topic (or group identifier/name/etc.).

Something like:
  emitter.on('my-topic/*', handlerForAllEventsInThisTopic);

This would be really helpful if we are dealing with different components that belong to the same section. This can be done with a consistent naming strategy, as well, but having this as a feature is more powerful. We can have a "topic-specific" handler for all events in the same group, but also event-specifc ones.

**Comment by redfox05** [comment]
Agreed, this would be very useful.

Alternatively, I also thought perhaps the emitter.on function could return a reference to the event listener, and then we can use that. For example

```
onComponentCreation() {
    this.listener1 = EventBus.on('updateMenu',  myFunction);
}
onComponentDestroy() {
    this.listender1.destroy();
}
```

Or something along those lines.
My use case for example, is several instances of the same Vue component, and after some investigation, I found the listeners were still firing for previous instances of the component that had since been destroyed, but the listeners remained. I had a check to ensure the right component id was present and return false if not right, but it still means many listeners getting triggered adding weight to everything.

**Comment by thiagoanselmo** [comment]
@redfox05 @adrianvoica 

Hello I had the same need, and fork the project and made it available here: https://github.com/thiagoanselmo/mitt-emitter see if it helps.

**Comment by developit** [comment]
There are already hundreds of modules that offer this, like WildEmitter. Adding pattern matching would increase size and performance overhead, even in the majority of cases where it's unused.

**Comment by thiagoanselmo** [comment]
@developit 

https://www.npmjs.com/package/mitt-emitter
