### ISSUE TITLE
Bug: type issue in ts@4.9+ with esm

### ISSUE THREAD

**Issue by Mister-Hope** [developit/mitt#173]
The package is shipping esm files, but package.json is missing `"type": "module"`

So typescript will assume users are importing a commonjs module, so it will report issues with:

```ts
import mitt from "mitt";

mitt(code)
```

Saying the expression is not callable.

That's because a cjs module will have it's module.exports on `default` key, so:

```ts
import mitt from "mitt";

mitt.default(code)
```

is ok to typescript, but it's not acually working (because we do have esm modules using `export default`)

**Comment by rschristian** [comment]
> So typescript will assume users are importing a commonjs module, so it will report issues with:

That then would be a bug in TS, which should be brought up to them. You can use the `.mjs` extension (as this module does) to specify the content of a file as being an ES module, regardless of the set package `type`. It's perfectly supported by the spec to offer formats that differ from the main package type; that's why `.mjs` & `.cjs` exist, after all.

> Regardless of the value of the "type" field, `.mjs` files are always treated as ES modules and `.cjs` files are always treated as CommonJS.

https://nodejs.org/api/packages.html#type

**Comment by Mister-Hope** [comment]
Yes, I already link the pr to the original issue, but not yet get any feedback.
