### ISSUE TITLE
why use sllice & map

### ISSUE THREAD

**Issue by zt123123** [developit/mitt#186]
Why use slice cloning, why use map instead of forEach, in my opinion, there is no need to use it here

https://github.com/developit/mitt/blob/6b41670516ed8e8b738612f60491995470aa63b3/src/index.ts#L107
https://github.com/developit/mitt/blob/6b41670516ed8e8b738612f60491995470aa63b3/src/index.ts#L108

**Comment by mwillbanks** [comment]
@zt123123 `forEach` has a lot of drawbacks, in general, most of the time it's syntactic sugar should not be used unless you understand the drawbacks.  This is a somewhat decent article about it: https://danthedev.com/stop-using-foreach/

no idea about the slice cloning but nothing is necessarily problematic with it... Array.from() would potentially be better but since the internal types are known, there is really no reason to stray...

**Comment by developit** [comment]
`.map()` is used because its a few bytes smaller when minified+gzipped.

`.slice()` is required because the Array of handlers can be mutated during iteration. Without first cloning the Array of handlers, mutations can cause an offset error:

```js
function first() {
    console.log('first');
}
function second() {
    handlers.splice(handlers.indexOf(second), 1);
    console.log('second');
}
function third() {
    console.log('third');
}
var handlers = [first, second, third];
handlers.forEach(handler => {
    handler();
});
// logs:
//   "first"
//   "second"
```

-- edit

`Array.from()` would be a performance penalty here, as it invokes the iterator protocol on the provided Array, which is much slower than index+length iteration - `.slice()` does not invoke the iterator protocol, as it is an Array method.
