### ISSUE TITLE
Bitwise operators question

### ISSUE THREAD

**Issue by KhaledElAnsari** [developit/mitt#56]
Hello, 

I'm here just to ask what is the main usage of the bit operators here? in the `off` function you're using `>>>` at [line 40](https://github.com/developit/mitt/blob/master/src/index.js#L40)
```javascript
all[type].splice(all[type].indexOf(handler) >>> 0, 1);
```

And in the old source code you used `~` also inside the `off` function at [line 34](https://github.com/KhaledElAnsari/mitt/blob/master/src/index.js#L34)

I just want to know why because I can't see a reason to use them and thank you in advance

**Comment by svincent** [comment]
I'll take a stab at this. 

## Short answer
The short answer is that the current version of this function gzips slightly better than the older one. Every byte matters when you only have 200 to work with.


## Longer answer

Both versions of the function are functionally identical. The reason for the change is size. gzip works by finding redundant strings and replacing them with a pointer to a previous occurrence of that sequence of characters. 

For example, the current version uses the string `all[type]` 6 times. That sequence of characters takes (I believe) 9 bytes to store, so raw all 6 appearances would take 54 bytes. But with gzip encoding they only take 19 bytes (I think).


## Bitwise Operations

Now if you're interested in *how* these implementations work, I'll do my best to give a quick rundown.

### Bitwise Not

The older version of the code uses a [bitwise not][1] (`~`) as a shorthand way of checking if indexOf returns a valid index. 

See, you can't just use the value returned by `indexOf()` in an `if` statement. `indexOf` returns 0 for the first index of an array, but 0 is falsy so it would fail the if-check. Similarly, `indexOf` returns -1 to indicate that the value is not in the array, but -1 is a truthy value, so it would pass an if-check.

You can work around this by performing a bitwise not on the return value.  This transforms 0 into a truthy value (`~0 === -1`) and -1 into a falsy one (`~ -1 === 0`). All other values will continue to be truthy.

### Zero-fill right shift

The new algorithm uses a [zero-fill right shift][1] (`>>>`) in a splice call on an array. Splice is used here to mutate the source array by removing a specific callback function from the list of callbacks. Before getting into how `>>>` works, first note now splice treats it's first argument:

> Index at which to start changing the array (with origin 0). If greater than the length of the array, actual starting index will be set to the length of the array. If negative, will begin that many elements from the end of the array (with origin 1).

As previously discussed indexOf will return -1 when the value isn't found in the array, but this will lead to unexpected behavior. And because of the strict byte limit we can't add additional if-checks or we'll bloat the file size. As such, we need to find a way to always call splice, but have it noop when the specified callback isn't found. That's where `>>>` comes in.

In the context of array indices, the most important thing to note a zero-fill right shift of 0 is that it's effectively does nothing to positive values (`24 >>> 0 === 24` and `0 >>> 0 === 0`), but it it completely changes the 'not found' return value (`-1 >>> 0 === 4294967295`). 4,294,967,295 is important here because it's the maximum possible index of an array in JavaScript.

In other words, if the supplied callback isn't found in the callback list, the splice call will try to remove the last possible value in the array. If no such value exists, then the operation completes without mutating the callback list.

Sources
- 0: [Bitwise Operators][0]
- 1: [Bitwise NOT][1] on MDN
- 2: [Zero-fill_right_shift][2] on MDN
- 3: [Why is a Javascript Array index at most 4294967294 but not 4294967295?][3] on StackOverflow
- 4: Section 9.4.2 of [ECMA-262 7th Edition][4] states that "A String property name P is an array index if and only if ToString(ToUint32(P)) is equal to P and ToUint32(P) is not equal to 2^32 ‑ 1."

[0]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#(Bitwise_NOT)
[2]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#>>>_(Zero-fill_right_shift)
[3]: https://stackoverflow.com/questions/12766422/why-is-a-javascript-array-index-at-most-4294967294-but-not-4294967295
[4]: http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf

**Comment by svincent** [comment]
@KhaledElAnsari Did my previous comment answer your question? If so, please close this issue. If not, I'd be happy to try again 😄

**Comment by KhaledElAnsari** [comment]
@svincent Thank you man I really appreciate it but let me get this straight the bit operator here is used just to avoid the non-existing element issue? nothing more?

**Comment by developit** [comment]
@KhaledElAnsari yup - it's a shortcut for this:

```js
let e = list(type),
    i = e.indexOf(handler);
if (i!==-1) e.splice(i, 1);
```

Just saves a few bytes.

**Comment by KhaledElAnsari** [comment]
I did some tests on Opera/Chrome and FireFox for the splice function with and without the bit operator and it turned out that it's faster with a bit operator! Almost half the time!! 

Thank you guys for your help :D
