### ISSUE TITLE
.off behaves inconsistently

### ISSUE THREAD

**Issue by sqal** [developit/mitt#65]
Check out this example https://jsfiddle.net/t2knuou6/

When i try to unbind multiple handlers basically immediately it won't remove all of them

**Comment by farskid** [comment]
That's happening because of the `map` function used in `emit` method. `Map` method is live on arrays and when `fn1` is called, it removes the first listener from the handlers, and that changes the length of the handlers array to __1__, since `map` already went through the 1st element in that array, it thinks that the iteration is done and gets out of the loop.
A fix for that would be to use a plain old `for loop` and make sure to capture the length of handlers array and the array itself before that loop starts since it's passed by reference.

```javascript
emit(type: string, evt: any) {
  const len = all.length, handlers = all[type].slice();
  for (var i = 0; i < len; i++) handlers[i].call(null, evt);
}
```
>NOTE: That may increase the size of the library to more thatn 200 bytes!

**Comment by developit** [comment]
I played with a bunch of options, and just adding a `slice()` into `emit()`fixes the issue in 187b (only 4 added bytes):

```js
emit(type: string, evt: any) {
  (all[type] || []).slice().map((handler) => { handler(evt); });
  (all['*'] || []).slice().map((handler) => { handler(type, evt); });
}
```

**Comment by Haroenv** [comment]
I'm curious why you chose to change it to `.slice().map` instead of using `.forEach`. That seems like less characters, no?
