### ISSUE TITLE
Wildcards to match segments?

### ISSUE THREAD

**Issue by atrauzzi** [developit/mitt#77]
Love seeing a new entry in the space for pubsub/events!  Definitely something [I keep thinking about](https://twitter.com/Omega_/status/1011067750792515585).

Have you considered adding support for wildcards to match segments within an event as opposed to being used as a catch-all?
I believe postaljs does this with the `#` and `*` characters.  Probably only need `*` to keep things minimalistic, unless there's a reason to differentiate matching one vs. many segments.

**Comment by developit** [comment]
Hi there! While I like the suggestion, I don't think this would be in keeping with the minimal nature of mitt. It's a subset of the use-case (firing events), and fairly easy to implement atop `*`. Since most folks wouldn't use the functionality, it seems wasteful.

However, it'd be a neat second library!

```js
import mitt from 'mitt';
import matching from 'matching-mitt';

const events = matching(mitt());
```

the above would simply augment mitt with pattern support:

```js
export default function matching(mitt) {
  let { on, off } = mitt;
  let cache = {};
  const mk = (pattern, fn, key) => cache[key = pattern+fn] || (cache[key] = (type, e) => {
    if (type.match(new RegExp('^'+pattern.replace(/\*/)+'$'))) return fn(e)
  });
  mitt.on = (type, fn) => type.match(/[#*]/) ? on('*', mk(type, fn)) : on(type, fn);
  mitt.off = (type, fn) => type.match(/[#*]/) ? off('*', mk(type, fn)) : off(type, fn);
  return mitt;
}
```

... or:

```js
export default function matchingMitt() {
  const all = {};
  const events = mitt(all);
  mitt.on('*', (type, e) => {
    for (let i in all) {
      if (i.length>1 && i.match(/[#*]/) && type.match(new RegExp('^'+i.replace(/\*/)+'$'))) {
        mitt.emit(i, e);
      }
    }
  });
}
```
