### ISSUE TITLE
Preact + Mitt Codepen Demo直接就是错误的

### ISSUE THREAD

**Issue by aammjian** [developit/mitt#86]
Preact + Mitt Codepen Demo 这个运行不起来

**Comment by dotproto** [comment]
Subject: Preact + Mitt Codepen Demo is directly wrong
Body: Preact + Mitt Codepen Demo This won't work

Via Google Translate.

After some brief digging it looks like [the Codepen project](http://codepen.io/developit/pen/rjMEwW?editors=0110) linked in README.md errors on load. The error appears to be caused by the `@connect` decorator on line 56. Near as I can tell this is caused by Babel not having `babel-decorator` or possibly `babel-plugin-transform-decorators-legacy` installed.

**Comment by developit** [comment]
Thanks for the repo and translation @dotproto! I've fixed the codepen demo by changing the decorator to a simple function call (`const Header = connect(class extends Component { ... })`)
